config/routes.rb
Hotspotter::Application.routes.draw do
  get "oauths/oauth"
  get "oauths/callback"
  get "password_resets/create"

  get "password_resets/edit"

  get "password_resets/update"

  post "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  default_url_options :host => "localhost:3000"

  get "logout" => "sessions#destroy", :as => :logout  
  get 'login' => 'user_sessions#new', :as => :login

  root :to => "welcome#index"
  
  resources :updates do 
      get 'like'
      get 'unlike'
      get 'get_firebase_data'
  end

  resources :sessions, :except => [:show, :update, :destroy]
  resources :users, :except => [:index]
  resources :password_resets

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	# render layout: false
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<% image_tag 'images/sizzle.jpg'%>


<div class = "row">
<div class="textFont normalText centerText biggerText largeMargin">
	Discover the Hottest Spots in Town
</div>
</div>

<div class = "row">
<div class = "centerText medMargin">
	<% if logged_in? %>
  		<%= link_to 'Logout', logout_path, class: 'btn' %>
    	<% else %>

    	<div class="btn btn-facebook icon-large icon-facebook">
  		<%= link_to 'Sign in with Facebook', auth_at_provider_path(:provider => :facebook), class: 'textFont linkText smallText' %>
  	</div></br></br>
  		  <%= link_to 'Sign In', new_session_path, class: 'textFont linkText smallText' %> &nbsp;&nbsp;&nbsp;
  		  <%= link_to 'Sign Up', new_user_path, class: 'textFont linkText smallText' %>
    <% end %>
</div>
</div>

<script>$('.centerText').hide();</script>
<script>$('.centerText').delay(500).fadeIn(2000);</script>