config/routes.rb
Hotspotter::Application.routes.draw do
  get "oauths/oauth"
  get "oauths/callback"
  get "password_resets/create"

  get "password_resets/edit"

  get "password_resets/update"

  post "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  default_url_options :host => "localhost:3000"

  get "logout" => "sessions#destroy", :as => :logout  
  get 'login' => 'user_sessions#new', :as => :login

  root :to => "welcome#index"
  
  resources :updates do 
      get 'like'
      get 'unlike'
      get 'get_firebase_data'
  end

  resources :sessions, :except => [:show, :update, :destroy]
  resources :users, :except => [:index]
  resources :password_resets

end

app/models/update.rb
class Update < ActiveRecord::Base
  belongs_to :user
  acts_as_likeable

  validates_presence_of :comment, :on => :create

  
  has_attached_file :attachment, :styles => { :medium => "300x300>", :small => "150x150>", :mini => "75x75" ,:thumb => "50x50>" }

  has_and_belongs_to_many :categories, :join_table => 'categories_updates'

end

app/controllers/updates_controller.rb
class UpdatesController < ApplicationController
	before_filter :require_login
	before_filter :require_user

	def index

		@updates = Update.order("created_at DESC").where("created_at > ?", Time.at(params[:after].to_i+1))

		# @updates = Update.all
		@update = @user.updates.build

		@heatmap_data = get_heatmap_data.to_json
		@update = @user.updates.build

		@updates_positions= get_updates_data.to_json
		# puts @heatmap_data 

		@lastUpdateTime = Time.now.localtime.strftime("%I:%M%p") 
		
	end

	def create
		@category = Category.new
		@update = @user.updates.build update_params

    @update.lat=@user.lat
    @update.long=@user.long
    @update.likes=0

   	@updates = Update.order("created_at DESC").where("created_at > ?", Time.at(params[:after].to_i+1))



	  	#Firebase.base_uri = 'https://hot-spotter.firebaseio.com/'

		# response = Firebase.push("updates",{username:@update.user.username, comment:@update.comment, likes:@update.likes, attachment:@update.attachment, lat:@update.lat , long:@update.long , created_at:@update.created_at})
	    # firebase_id = Update.last.id.to_i
	  	# Firebase.base_uri = 'https://hot-spotter.firebaseio.com/'
		# response = Firebase.push("updates/",{username:@update.user.username, comment:@update.comment, likes:@update.likes, attachment:@update.attachment, lat:@update.lat , long:@update.long , created_at:Time.now.localtime.strftime("%I:%M%p")})
		# response = Firebase.push( firebase_id ,{username:@update.user.username, comment:@update.comment, likes:@update.likes, attachment:@update.attachment, lat:@update.lat , long:@update.long , created_at:Time.now.localtime.strftime("%I:%M%p")})
		
		respond_to do |format|
	    if @update.save
	    	  	format.html {redirect_to updates_path} 
      			# format.js {render json: @updates, content_type: 'text/json' }
      			format.js
	   	  		# redirect_to updates_path, notice: "Update posted!"
	    else
	      	format.html{ render :updates }
	      	format.js {}
	    end
	  end
	  
	end

	def destroy
		@update = Update.find(params[:id])
		@update.attachment = nil
		@update.save
		redirect_to updates_path
	end

	def like
		@update = Update.find(params[:update_id])
		
		#updating the likes for that update
		if current_user.likes?(@update)
			current_user.unlike!(@update)
			@update.likes -=1
			@update.save!
			update_owner = @update.user
			update_owner.likes -=1
			update_owner.save!
		else
			current_user.like!(@update)
			@update.likes +=1
			@update.save!
			update_owner = @update.user
			update_owner.likes+=1
			update_owner.save!
		end

		respond_to do |format|
			format.html { redirect_to updates_path }

			# Add error handling if necessary
			format.json { render :json => {error: false} }
		end
	end

	def get_heatmap_data
		users = User.all 
		users.map { |user| {:lat => user.lat, :lng => user.long} }
	end


	def get_updates_data
		updates = Update.all 
		updates.map { |update| {:lat => update.lat, :lng => update.long, :cat => update.category_ids[0]} }
	end
	
	def get_firebase_data
		Firebase.base_uri = 'https://hot-spotter.firebaseio.com/'
		firebase_updates = Firebase.get("updates")

		firebase_updates.body.each_key do |key|
      		updateTime = firebase_updates.body[key]["created_at"]
      		if( updateTime >= @lastUpdateTime)
      			newUpdate.push(firebase_updates.body[key])
      		end
    	end 
    	@lastUpdateTime = updateTime


    	respond_to do |format|
    		format.json {render :json => 'newUpdate'}
    	end
	end

	protected
	
	def require_user
		@user = current_user
	end

	private

	def update_params
		params.require(:update).permit(:comment,:likes, :attachment, :lat, :long, :user_id, :category_ids =>[])
	end
end

app/helpers/updates_helper.rb
module UpdatesHelper
end

app/views/updates/_displayCategories.html.erb
<div class = "circle lightest">
	<div class = 'category textFont normalText smallerText leftText darkText'>
		Restaurants
	</div>
</div>
<div class = "circle light">
	<div class = 'category textFont normalText smallerText leftText darkText'>
		Night Life
	</div>
</div>
<div class = "circle normal">
	<div class = 'category textFont normalText smallerText leftText darkText'>
		Entertainment
	</div>
</div>
<div class = "circle medium">
  <div class = 'category textFont normalText smallerText leftText darkText'>
    Athletic
  </div>
</div>
<div class = "circle dark">
  <div class = 'category textFont normalText smallerText leftText darkText'>
    Family
  </div>
</div>
<div class = "circle darkest">
  <div class = 'category textFont normalText smallerText leftText darkText'>
    All 
  </div>
</div>

<script type="text/javascript">
window.HeatMapModule = (function() {
  var updatesPositions;

   $('.lightest').click( function() {
      heatmap.setMap(null);
      var j=0;
      var heatData = new Array;
      for (var i=0; i<updatesPositions.length ;i++)
      { 
         if (updatesPositions[i]['cat'] == 7)
         {
           lat= updatesPositions[i]['lat'];
           lng= updatesPositions[i]['lng'];
           heatData[j] = new google.maps.LatLng(lat, lng);
           j=j+1;
         }    
      }
      heatmap = new google.maps.visualization.HeatmapLayer({
         data: heatData,
         radius: 15,
         opacity: 0.8
      });
      heatmap.setMap(map);  
     });

   $('.light').click( function() {
      heatmap.setMap(null);
      var j=0;
      var k=0
      var heatData = new Array;
      for (var i=0; i<updatesPositions.length ;i++)
      { 
         if (updatesPositions[i]['cat'] == 8)
         {
           lat= updatesPositions[i]['lat'];
           lng= updatesPositions[i]['lng'];
           heatData[j] = new google.maps.LatLng(lat, lng);
           j=j+1;
         }      
      }
      heatmap = new google.maps.visualization.HeatmapLayer({
         data: heatData,
         radius: 15,
         opacity: 0.9
      });
      heatmap.setMap(map);
     });

   $('.normal').click( function() {
      heatmap.setMap(null);
      var j=0;
      var k=0
      var heatData = new Array;
      for (var i=0; i<updatesPositions.length ;i++)
      { 
         if (updatesPositions[i]['cat'] == 9)
         {
           lat= updatesPositions[i]['lat'];
           lng= updatesPositions[i]['lng'];
           heatData[j] = new google.maps.LatLng(lat, lng);
           j=j+1;
         }   
      }
      heatmap = new google.maps.visualization.HeatmapLayer({
         data: heatData,
         radius: 15,
         opacity: 0.9
      });
      heatmap.setMap(map);
     });

   $('.medium').click( function() {
      heatmap.setMap(null);
      var j=0;
      var k=0
      var heatData = new Array;
      for (var i=0; i<updatesPositions.length ;i++)
      { 
         if (updatesPositions[i]['cat'] == 10)
         {
           lat= updatesPositions[i]['lat'];
           lng= updatesPositions[i]['lng'];
           heatData[j] = new google.maps.LatLng(lat, lng);
           j=j+1;
         }      
      }
      heatmap = new google.maps.visualization.HeatmapLayer({
         data: heatData,
         radius: 15,
         opacity: 0.9
      });
      heatmap.setMap(map);
     });

    $('.dark').click( function() {
      heatmap.setMap(null);
      var j=0;
      var k=0
      var heatData = new Array;
      var heatData_other = new Array;
      for (var i=0; i<updatesPositions.length ;i++)
      { 
         if (updatesPositions[i]['cat'] == 11)
         {
           lat= updatesPositions[i]['lat'];
           lng= updatesPositions[i]['lng'];
           heatData[j] = new google.maps.LatLng(lat, lng);
           j=j+1;
         }      
      }
      heatmap = new google.maps.visualization.HeatmapLayer({
         data: heatData,
         radius: 15,
         opacity: 0.9
      });
      heatmap.setMap(map);
     });
       $('.darkest').click( function() {
      heatmap.setMap(null);
      var j=0;
      var k=0
      var heatData = new Array;
      for (var i=0; i<updatesPositions.length ;i++)
      { 
         lat= updatesPositions[i]['lat'];
         lng= updatesPositions[i]['lng'];
         heatData[j] = new google.maps.LatLng(lat, lng);
         j=j+1;
      }
      heatmap = new google.maps.visualization.HeatmapLayer({
         data: heatData,
         radius: 10
      });
       heatmap.setMap(map);
     });

      return {
    start: function(opts) {
      updatesPositions = opts.updatesPositions;
    }
  };
}());

</script>

app/views/updates/_displayImgIcons.html.erb
<% if  update.user.facebook_img %>
      <%= link_to (user_path(update.user_id)) do %>
          <a href="#"> <div class="profileIconMini">
          <%= image_tag "#{update.user.facebook_img}?type=small" %></br></div> 
          </a>
      <% end %>  
<% else %>
      <%= link_to (user_path(update.user_id)) do %>
        <div class="profileIconMini linkText" style="display: block; background-image: url( <%=update.user.avatar.url(:thumb) %>);"></br></div>
      <% end %> 
<% end %> 

app/views/updates/_displayUpdates.html.erb
<% @updates.each do |update| %>
    <a href="#"> <div id="comments" class = "updateContainer" data-lat="<%= update.lat %>" data-lng="<%= update.long %>" data-time= "<%= update.created_at.to_i%>"
      data-img="<%= render 'returnFbookOrAvatar', :update => update %>"></a>
      <div class = "updateImage">
          <%= render 'displayImgIcons', :update => update %>
      </div>
      <div class = "updateComment textFont normalText darkText rightText smallestText">
              <div class="updateText leftText">
                  <% if update.attachment_file_size != nil %>
                    <div class = 'imageAttachment'>
                        <%= image_tag update.attachment.url(:thumb) %>
                    </div> 
                  <% end %>
                  
                  <%= update.user.username %></br> 
                  <div class = "boldText darkText smallestText">
                  <%= update.comment %></div>
                  <%= update.created_at.localtime.strftime('%I:%M%p')%> 
              </div>
              <div class= "updateLike">
                  <% if current_user.likes?(update) %>
                      <%= link_to update_like_url(update), :class => "update-like" do %>
                        <div class="heart my-like" title="Like"></div>
                      <%end%>
                  <% elsif !current_user.likes?(update) %>
                    <%= link_to update_like_url(update), :class => "update-like" do %>
                      <div class="heart" title="Like"></div>
                    <% end %>
                  <% end %>

                  <span class="like-count"><%= update.likes %></span>
              </div>
        </div> 
    </div>
<% end %>

<script> $('.outerUpdateContainer').hide() </script>
<script> $('.outerUpdateContainer').delay(1500).fadeIn(1500); </script>


<!-- <input type='text' id='messageInput' placeholder='Message...'> -->

app/views/updates/_returnFbookOrAvatar.html.erb
	<% if  update.user.facebook_img %>
	        <%="#{update.user.facebook_img}?type=small" %> 
	<% else %>
	        <%=update.user.avatar.url(:thumb) %>)
	<% end %> 

app/views/updates/create.js.erb
// alert("<%= escape_javascript(render(:partial => '/updates/displayUpdates')) %>");
var x = $(".updateContainer");
x.html("<%= escape_javascript(render(:partial => '/updates/displayUpdates')) %>");
// $(".updateContainer").html("<%= escape_javascript(render(:partial => '/updates/displayUpdates')) %>";

app/views/updates/index.html.erb
<script type="text/javascript">
    // var toggleMe = 0;

    $(".profileIcon").click(function() {
      // if (toggleMe == 0){
        // $('#profileColumn').fadeTo(1500, 0.5);
        // $('#profileColumn').show( 'slide', {direction: 'left'}, 'slow' );

        // var containerWidth = $('.containerFull').css('width','80%');
        // var width = $('.colRight70').width();
        // $("#googleMap").css('width' , width - width*0.06);
        $('#profileColumn').toggle();
        $('.containerFull').toggleClass('decreaseWidth');
        // $('#googleMap').toggleClass('decrease');


      //   toggleMe = 1;
      // }
      // else{
      //   // $('#profileColumn').fadeTo(1500, 0);
      //   // $('#profileColumn').hide( 'slide', {direction: 'right'}, 'slow' );
      //   $('.containerFull').css('width','100%');
      //   var width = $('.colRight70').width();
      //   $("#googleMap").css('width' , width - width*0.06);
      //   $('#profileColumn').css('width', 0);
      //   toggleMe = 0;
      // }
   });


</script>

<div class= "row textFont thinText bigText hoverText">
    <div class='colLeft30'>
      <a class="modalLink" href="#"> What's Sizzlin </a>
    </div>
    <div class='colRight70'>
      <%= render 'displayCategories' %>
      <div class="overlay"></div>
      <div class="modal textFont thinText smallestText">
        <a href="#" class="closeBtn textFont thinText smallestText"> x </a>
              
        <%= form_for @update, :remote => true, authenticity_token: true do |f|  %>
        <div class="centerText textFont thinText normalText">What's Sizzlin?</div> 
              <%= f.text_field :comment, {id: 'commentBox'} %></br>
              <%= f.file_field :attachment, {id: 'attachPhoto'} %>
              <%= f.submit 'Post Update', {id: 'submitPost'} %>

                <div id="categorySelection">
                    <% for category in Category.find(:all) %>
                        <%= check_box_tag "update[category_ids][]", category.id, @update.categories.include?(category) %>
                        <%= category.update_type %>
                    <%end%>
                </div>
        <% end %>   
      </div>
    </div>
</div>      
<div class="colLeft30">
  <div class = "outerUpdateContainer">
    <div id = "updateContent">
      <a href="#"> <div id="comments" class = "updateContainer"></a>
      <%= render 'displayUpdates' %>
       </div>
     </div> 
  </div>
</div>
<div class="colRight70">
    <div id="searchBox">
        <input id="addressInput" type="textbox" class= "textFont darkText boldText">
        <input type="button" class = "arrow_box" onclick="codeAddress()">
    </div>
    <div id="googleMap" style="width:500px;height:380px;"></div>
</div>


<% if logged_in? %>
      <%#= link_to 'Post Update', new_update_path, class: 'btn' %>
<% else %>
      <%= link_to 'Sign In to Update', new_session_path, class: 'btn' %>
<% end %>  

<script> $('.modalLink').hide() </script>
<script> $('.modalLink').delay(500).fadeIn(1500); </script>  
<script> $('#googleMap').hide() </script>
<script> $('#googleMap').delay(100).fadeIn(2500); </script>  
<script> $('#searchBox').hide() </script>
<script> $('#searchBox').delay(1500).fadeIn(1500); </script>  

<script> $('#submitPost').click( function() {$('.overlay').delay(100).fadeOut(1000)}); </script>  
<script> $('#submitPost').click( function() {
              $('.modal').delay(100).fadeOut(1000);
              $('.commentBox').val('');
            }); </script>  

<script type="text/javascript">
  $('#sizzleButton').modal({
    trigger: '#sizzleButton',
    olay:'div.overlay',
    modals:'div#newSizzle',
    animationEffect: 'slidedown',
    animationSpeed: 400,
    moveModalSpeed: 'slow',
    background: '00c2ff',
    opacity: 0.8,
    openOnLoad: false,
    docClose: true,
    closeByEscape: true,
    moveOnScroll: true,
    resizeWindow: true,
    video:'http://player.vimeo.com/video/9641036?color=eb5a3d',
    close:'.closeBtn'
  });
</script>
<script>
  $(document).ready( function() {
    window.MapModule.start({
        userLocations: <%= @heatmap_data.html_safe %>
    },5000);
    resize();

  });
</script>
<script>
$(document).ready( function() {
  window.HeatMapModule.start({
      updatesPositions: <%= @updates_positions.html_safe %>
  },5000);
  resize();
});
</script>

app/views/updates/new.html.erb
<div id='messagesDiv'></div>
<input type='text' id='nameInput' placeholder='Name'>
<input type='text' id='messageInput' placeholder='Message...'>

<script>
  var messagesRef = new Firebase('https://hot-spotter.firebaseio.com/');

  // When the user presses enter on the message input, write the message to firebase.
  $('#messageInput').keypress(function (e) {
    if (e.keyCode == 13) {
      var name = $('#nameInput').val();
      var text = $('#messageInput').val();
      messagesRef.push({name:name, text:text});
      $('#messageInput').val('');
    }
  });

  // Add a callback that is triggered for each chat message.
  messagesRef.limit(10).on('child_added', function (snapshot) {
    var message = snapshot.val();
    $('<div/>').text(message.text).prepend($('<em/>')
      .text(message.name+': ')).appendTo($('#messagesDiv'));
    $('#messagesDiv')[0].scrollTop = $('#messagesDiv')[0].scrollHeight;
  });
</script>